services:
  api:
    build: ./backend
    ports:
      - "8001:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=ad_builder.settings

  web:
    build: ./frontend
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://localhost:8001/api
    depends_on:
      - api 